document.addEventListener('DOMContentLoaded', async () => {
  const session = Auth.requireRole('admin'); if (!session) return;
  document.getElementById('adminName').textContent = session.name;
  document.getElementById('logoutBtn').addEventListener('click', () => { Auth.logout(); window.location.href = '../login.html'; });
  const listEl = document.getElementById('surplusList'); let batches = []; let recipients = [];
  document.getElementById('recipientForm').addEventListener('submit', async event => { event.preventDefault(); try { await API.createRecipient({ name: document.getElementById('recipientName').value.trim(), contactPerson: document.getElementById('recipientContact').value.trim(), city: document.getElementById('recipientCity').value.trim(), capacityKg: Number(document.getElementById('recipientCapacity').value) }); event.target.reset(); await load(); Notify.toast('Recipient saved.', 'success'); } catch (error) { Notify.toast(error.message, 'error'); } });
  function render() { if (!batches.length) { listEl.innerHTML = '<p class="empty-state">No surplus items logged yet - send items from Inventory.</p>'; return; } listEl.innerHTML = batches.map(item => `<div class="card" data-id="${item._id}" style="margin-bottom:14px;"><div class="forecast-card__head"><div><span class="card__eyebrow">${item.quantityKg} kg · ${item.weightLbs.toFixed(2)} lbs</span><div class="card__title" style="margin-bottom:4px;">${item.foodItem}</div></div><div style="text-align:right;"><span class="badge badge--info"><i class="badge__dot"></i>${item.status}</span><div class="safety-remaining" style="margin-top:4px;">Safe until ${new Date(item.safeUntil).toLocaleString()}</div></div></div><div class="surplus-row__actions" style="margin-top:10px;"><select data-action="recipient"><option value="">Select recipient</option>${recipients.map(r => `<option value="${r._id}">${r.name}</option>`).join('')}</option></select><button class="btn btn--outline btn--sm" data-action="match" ${item.status !== 'Pending' ? 'disabled' : ''}>Match</button><button class="btn btn--primary btn--sm" data-action="deliver" ${item.status !== 'Matched' ? 'disabled' : ''}>Mark delivered</button></div></div>`).join(''); }
  async function load() { try { [batches, recipients] = [(await API.surplus()).batches, (await API.recipients()).recipients]; render(); } catch (error) { Notify.toast(error.message, 'error'); } }
  listEl.addEventListener('click', async event => { const button = event.target.closest('button[data-action]'); if (!button) return; const card = button.closest('[data-id]'); const batch = batches.find(item => item._id === card.dataset.id); try { if (button.dataset.action === 'match') { const recipientId = card.querySelector('select').value; if (!recipientId) throw new Error('Select a recipient first.'); await API.matchSurplus(batch._id, recipientId); } else await API.updateSurplus(batch._id, 'Delivered'); await load(); Notify.toast('Surplus status updated.', 'success'); } catch (error) { Notify.toast(error.message, 'error'); } });
  await load();
});
